#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #11
# Public test 5 (public5)
#
# Tests the program with two filenames on the command line, so two threads
# will be created.  The files are much larger than those in the previous
# test.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./wc-threaded.x public5.inputdata1 public5.inputdata2
