#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #11
# Public test 7 (public7)
#
# Tests the program with two filenames on the command line, so two threads
# will be created.  The files are the same as those in the fourth public
# test, so the results should be the same.  The difference is that this test
# uses valgrind to check for memory leaks and corruption of the heap.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

valgrind -q --leak-check=full --trace-children=yes --error-exitcode=100 \
  ./wc-threaded.x public4.inputdata1 public4.inputdata2

if ($status == 0) then
  # normal exit
  echo "Success!  wc-threaded.x didn't have any memory problems."
  exit 0
else
  # error exit
  echo "Waaah!  wc-threaded.x had memory leaks or other memory problems."
  exit -1
endif

