#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #11
# Public test 4 (public4)
#
# Tests the program with two filenames on the command line, so two threads will
# be created.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./wc-threaded.x public4.inputdata1 public4.inputdata2
