#!/bin/tcsh -f

# CMSC 216, Spring 2023, Project #11
# Public test 2 (public2)
#
# Tests the program with just one filename on the command line, meaning only
# one thread will be created (besides the main thread).  The file does not
# exist though, so it should have zero lines, words and characters.
#
# (c) Larry Herman, 2023.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./wc-threaded.x public2.inputdata
